### ISSUE TITLE
parse-string accepts invalid json string

### ISSUE THREAD

**Issue by Satshabad** [dakrone/cheshire#79] opened 2015-05-04 23:15 UTC
When I do:

```
 (cheshire.core/parse-string "\"foo\": \"bar\"}")
```

I get

```
"foo"
```

note the lack of a starting `{`

I would expect this to throw an exception instead. May be linked to https://github.com/dakrone/cheshire/issues/65

It must see everything after `"foo"` as junk...

**Comment by cespare** [comment] 2015-05-04 23:19
This is a duplicate of #65.

**Comment by dakrone** [comment] 2017-08-15 21:55
closed in #122

**Closed by dakrone** 2017-08-15 21:55 UTC
